name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ios-build:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-ios
        profile: minimal
        override: true
        
    - name: Install iOS target
      run: rustup target add aarch64-apple-ios
        
    - name: Build libptrscan
      run: |
        cd libptrscan
        cargo build --release --target aarch64-apple-ios --verbose
        mkdir -p ../target/aarch64-apple-ios/release/lib
        ls -la target/aarch64-apple-ios/release/deps/
        cp target/aarch64-apple-ios/release/deps/libptrscan-*.a ../target/aarch64-apple-ios/release/lib/libptrscan.a
        ls -la ../target/aarch64-apple-ios/release/lib/
        
    - name: Build command tool
      run: |
        cd command
        RUSTFLAGS="-L ../target/aarch64-apple-ios/release/lib" cargo rustc --release --target aarch64-apple-ios --verbose -- -l static=ptrscan -L ../target/aarch64-apple-ios/release/lib
        
    - name: Create Release Bundle
      run: |
        mkdir -p release
        cp target/aarch64-apple-ios/release/ptrscan release/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-release
        path: release/
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/ptrscan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
